M48
; DRILL file {KiCad 9.0.2} date 2026-02-26T22:18:23+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-26T22:18:23+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X215.25Y-219.075
X215.25Y-236.025
X224.06Y-253.07
M30
